"""rename email to login

Revision ID: c63bbc8e7381
Revises: 8a9b34df929d
Create Date: 2026-02-25 17:37:32.119965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c63bbc8e7381'
down_revision: Union[str, Sequence[str], None] = '8a9b34df929d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email', new_column_name='login')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'login', new_column_name='email')
    # ### end Alembic commands ###
